apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: object-detection-ingress
spec:
  rules:
  - host: video-processing.com
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: detection-app-service
            port: 
              number: 80